project/webAdmin/routes.py
from flask import Blueprint,redirect,flash, url_for,render_template
from flask_login import current_user, login_required, logout_user
from flask_bcrypt import generate_password_hash
import os
import secrets
from PIL import Image
from flask import current_app
from project.webAdmin.forms import UpdateUserForm,DeleteForm, FilterUser
from project.webUserAuth.forms import RegisterUserForm
from project.webAppointment.forms import CreateAppointment, FilterAppointment

import pdb
from project.Database.database import db

admin=Blueprint('admin',__name__,template_folder='templates',static_folder='static', static_url_path='/admin/static')

@admin.route("/myAppointments", methods=["GET", "POST"])
@login_required
def my_appointments():
    '''list all of my appointments'''
    context_data= {'page_title':'My Appointments','main_head':'My Appointments'}
    filter_form = FilterAppointment()

    all_appointments_length = 0
    appointments_list = []

    if current_user.type == "Client":
        appointments_list=db.get_all_records_cond("salon_appointment",f"user_id={current_user.user_id}")
        all_appointments_length = len(appointments_list)
    else:
        appointments_list=db.get_all_records_cond("salon_appointment",f"employee_id={current_user.user_id}")
        all_appointments_length = len(appointments_list)
        
    if filter_form.validate_on_submit():   
        if filter_form.filter.data != "all":
            if current_user.type == "Client":
                appointments_list=db.get_all_records_cond("salon_appointment",f"user_id={current_user.user_id} and status = '{filter_form.filter.data}'")
            else:
                appointments_list=db.get_all_records_cond("salon_appointment",f"employee_id={current_user.user_id} and status = '{filter_form.filter.data}'")
            
        if filter_form.sort.data == "date":
            appointments_list.sort(key=lambda appointment: appointment[3])
        
        if filter_form.sort.data == "slot":
            appointments_list.sort(key=lambda appointment: appointment[4])
        
        if filter_form.sort.data == "room":
            appointments_list.sort(key=lambda appointment: appointment[5])
        
        if filter_form.sort.data == "user":
            if current_user.type == "Client":
                appointments_list.sort(key=lambda appointment: appointment[9])
            else:
                appointments_list.sort(key=lambda appointment: appointment[8])
    
    return render_template("myAppointments.html",context=context_data,appointments_list=appointments_list, filter_form=filter_form, current_user=current_user, all_appointments_length=all_appointments_length)

@admin.route("/AppointmentInfo/<id>")
@login_required
def app_info(id):
    '''info for specific appointment'''
    context_data= {'page_title':'Appointment Info','main_head':'More Appointment Info'}
    appointment=db.get_one_record("salon_appointment",f"appointment_id={id}")
    report_list=db.get_all_records_cond("salon_report",f"appointment_id={id}")
    service=db.get_one_record("salon_service", f"service_id = {appointment[10]}")
    if current_user.access!=4 and current_user.user_id!=appointment[6] and current_user.user_id!=appointment[7]:
        flash("You do NOT have access to this page.","error")
        db.edit_record("is_active=2",f"where user_id={current_user.user_id}","salon_user")
        return redirect(url_for("main_bp.home"))

    return render_template("moreInfo.html",context=context_data,appointment=appointment,report_list=report_list,service=service)

@admin.route("/Profile")
@login_required
def profile():
    '''User Profile'''
    context_data= {'page_title':'Profile','main_head':'Profile'}

    return render_template("profile.html",context=context_data)

@admin.route("/Users", methods=["GET", "POST"])
@login_required
def users():
    '''all users'''
    context_data= {'page_title':'Profile','main_head':'Profile'}
    all_users=db.get_all_records("salon_user")
    filter_form = FilterUser()
    if current_user.access==4:
        if filter_form.validate_on_submit():
            if filter_form.type.data != "All":
                all_users = db.get_all_records_cond("salon_user", f"user_type = '{filter_form.type.data}' and lower(user_name) like '%{filter_form.username.data.lower()}%'")
            else:
                all_users = db.get_all_records_cond("salon_user", f"lower(user_name) like '%{filter_form.username.data.lower()}%'")
    else:
        flash("You do NOT have access to this page.","error")
        db.edit_record("is_active=2",f"where user_id={current_user.user_id}","salon_user")
        return redirect(url_for("main_bp.home"))
    return render_template("allUsers.html",context=context_data,users=all_users,filter_form=filter_form)


@admin.route("/Update/<user_id>",methods=['GET','POST'])
@login_required
def update(user_id):
    '''Update user'''
    context_data= {'page_title':'Update Profile','main_head':'Update Profile'}
    form=UpdateUserForm()
    user_to_update=db.get_one_person(f"user_id={user_id}")
    if user_id!=str(current_user.user_id) and current_user.access!=4:
        flash("You do NOT have access to this page.","error")
        db.edit_record("is_active=2",f"where user_id={current_user.user_id}","salon_user")
        return redirect(url_for("main_bp.home")) 
    if user_to_update[2] in ["Client","Admin"] and current_user.access in [2,4]:
        form.type.choices = [
            ("password", "Password"),
            ("email", "Email"),
            ("phone_number", "Phone Number"),
            ("address", "Address"),
            ("age", "Age"),
            ("user_image", "Profile Picture"),
            ("access_level", "Access Level"),
            ("is_active", "Is Active")
        ]
    elif user_to_update[2]=="Employee" and current_user.access in [2,4]:
        form.type.choices = [
            ("password", "Password"),
            ("email", "Email"),
            ("phone_number", "Phone Number"),
            ("address", "Address"),
            ("age", "Age"),
            ("specialty", "Specialty"),
            ("pay_rate", "Pay rate"),
            ("user_image", "Profile Picture"),
            ("access_level", "Access Level"),
            ("is_active", "Is Active")
        ]
    elif user_to_update[2]=="Client":
        form.type.choices = [
            ("password", "Password"),
            ("email", "Email"),
            ("phone_number", "Phone Number"),
            ("address", "Address"),
            ("age", "Age"),
            ("user_image", "Profile Picture"),
        ]
    elif user_to_update[2]=="Employee":
        form.type.choices = [
            ("password", "Password"),
            ("email", "Email"),
            ("phone_number", "Phone Number"),
            ("address", "Address"),
            ("age", "Age"),
            ("specialty", "Specialty"),
            ("pay_rate", "Pay rate"),
            ("user_image", "Profile Picture"),
        ]
    if form.validate_on_submit():
        field=form.type.data
        to_update=getattr(form,field).data
        if field=='user_image':
            new_file=save_file(form.user_image.data)
            set_cols=f"{field}='{new_file}'"
        elif field=='password':
            to_update=generate_password_hash(form.password.data).decode('utf-8')
            set_cols=f"{field}='{to_update}'"
        elif field=='access_level':
            pdb.set_trace()
            access=form.access_level.data
            if access in ['2','3','4']:
                set_cols=f"{field}={access}, user_type='Admin'"
            else:
                set_cols=f"{field}={access}"
        elif field=='is_active':
            active=form.is_active.data
            set_cols=f"{field}={active}"
        else:
            set_cols=f"{field}='{to_update}'"
        cond=f"WHERE user_id={user_id}"
        db.edit_record(set_cols,cond,"salon_user")
        
        db.add_new_log(current_user.username,f"Edited {user_to_update[4]}'s {field}")
        
        flash(f'{field} Updated','success')
        return redirect(url_for('main_bp.home'))
    return render_template("update.html",context=context_data,current_user=current_user,form=form,user=user_to_update)

@admin.route("/delete/<user_id>",methods=["POST","GET"])
@login_required
def delete(user_id):
    '''delete user'''
    user_exist=db.get_one_person(f"user_id={user_id}")
    if user_exist:
        cond=f"SALON_USER WHERE user_id={user_id}"
        if user_id==str(current_user.user_id):
            user_identity=user_id
            logout_user()
            db.delete_record(cond)
            db.add_new_log(user_identity,f"Deleted user {user_id}")
            flash("User Deleted",'success')
            return redirect(url_for('auth_bp.login'))
        else:
            if current_user.access==4:
                db.delete_record(cond)
                db.add_new_log(user_id,f"Deleted user {user_id}")
                flash("User Deleted",'success')
                return redirect(url_for('admin.dashboard'))
            else:
                flash("You do NOT have access to this page.","error")
                db.edit_record("is_active=2",f"where user_id={current_user.user_id}","salon_user")
                return redirect(url_for("main_bp.home"))
    else:
        flash("User does not exist",'error')
        redirect(url_for("admin.users"))

def save_file(form_file):
    '''save file'''
    random_file_name=secrets.token_hex(8)
    f_name,f_ext=os.path.splitext(form_file.filename)
    new_filename=random_file_name+f_ext

    new_file_path=os.path.join(current_app.root_path,'static/images',new_filename)

    i=Image.open(form_file)
    image_new_size=(150,150)
    i.thumbnail(image_new_size)

    i.save(new_file_path)
    return new_filename

@admin.route('/registerAdd', methods=["GET", "POST"])
def register():
    '''register new user'''
    form = RegisterUserForm()
    context_data= {
        'page_title':'Sign Up',
        'main_head':'Sign up' 
    }

project/webAdmin/templates/allLogs.html
{% extends 'base.html' %}
{% block css %}
<link rel="stylesheet" href="{{url_for('static', filename='css/all-records.css')}}">
<link rel="stylesheet" href="{{url_for('admin.static', filename='css/all-logs.css')}}">
{% endblock %}
{% block info_section %}    
    {% for log in logs %}
    <section class="allRecords">
        <p>Username: {{log[1]}}</p>
        <p>Action: {{log[2]}}</p>
        <p>Date: {{log[3]}}</p>
    </section>
    {% endfor %}
{% endblock info_section %}

project/webAdmin/templates/allUsers.html
{% extends 'base.html' %}
{% block css %}
<link rel="stylesheet" href="{{url_for('static', filename='css/all-records.css')}}">
<link rel="stylesheet" href="{{url_for('admin.static', filename='css/all-users.css')}}">
{% endblock %}
{% block info_section %}    
    {% for user in users %}
    <section class="allRecords">
        <p>Name: {{user[4]}}</p>
        <p>Type: {{user[2]}}</p>
        <p>Access Level: {{user[3]}}</p>
        <p>Active Level: {{user[1]}}</p>
        <p>Email: {{user[5]}}</p>
        <p>Phone Number: {{user[8]}}</p>
        <p>Address: {{user[9]}}</p>
        <p>Age: {{user[10]}}</p>
        <section class="record-buttons">
            <a href="{{url_for('admin.update',user_id=user[0])}}">Click to update this profile</a>
            <a onclick="return confirm('Press OK to delete')" href="{{url_for('admin.delete',user_id=user[0])}}">Click to Delete Profile</a>
        </section>
    </section>
    {% endfor %}
{% endblock info_section %}

{% block forms_section %}
    <form method="POST">
        {{ filter_form.hidden_tag() }}

        <fieldset>
            <legend>Status:</legend>
            {{ filter_form.username(placeholder = "Enter a username") }}
        </fieldset>
        
        <fieldset>
            <legend>Sort:</legend>

            {% for subfield in filter_form.type %}
                {{ subfield }}
                {{ subfield.label }}
            {% endfor %}
        </fieldset>

        {{ filter_form.submit }}
    </form>
{% endblock %}

project/webAdmin/templates/dashboard.html
{% extends 'base.html' %}
{% block css %}
<link rel="stylesheet" href="{{url_for('static', filename='css/all-records.css')}}">
<link rel="stylesheet" href="{{url_for('admin.static', filename='css/dashboard.css')}}">
{% endblock %}
{% block info_section %}
<section class="dashboard-block">
    <h1>List of Users</h1>
    {% for user in users %}
    <section class="allRecords">
        <p>Name: {{user[4]}}</p>
        <p>Type: {{user[2]}}</p>
        <p>Access Level: {{user[3]}}</p>
        <p>Active Level: {{user[1]}}</p>
        <p>Email: {{user[5]}}</p>
        <p>Phone Number: {{user[8]}}</p>
        <p>Address: {{user[9]}}</p>
        <p>Age: {{user[10]}}</p>
        <section class="record-buttons">
            <a href="{{url_for('admin.update',user_id=user[0])}}">Click to update this profile</a>
            <a onclick="return confirm('Press OK to delete')" href="{{url_for('admin.delete',user_id=user[0])}}">Click to Delete Profile</a>
        </section>
    </section>
    {% endfor %}
</section>
<section class="dashboard-block">
    <h1>List of Logs</h1>
    {% for log in logs %}
    <section class="allRecords">
        <p>Username: {{log[1]}}</p>
        <p>Action: {{log[2]}}</p>
        <p>Date: {{log[3]}}</p>
    </section>
    {% endfor %}
</section>
<section class="dashboard-block">
    <h1>List of appointments</h1>
    {% for appointment in appointments %}
        <section class="allRecords">
            <p>Appointment ID: {{appointment[0]}}</p>
            <p>Status: {{appointment[1]}}</p>
            <p>Date: {{appointment[3]}}</p>
            <p>Time Slot: {{appointment[4]}}</p>
            <p>Venue: {{appointment[5]}}</p>
            <p>Customer: {{appointment[8]}}</p>
            <p>Employee: {{appointment[9]}}</p>
            <section class="record-buttons">
                <a href="{{url_for('appointment_bp.update_appointment', appointment_id=appointment[0])}}">Update this appointment</a>
                <a onclick="return confirm('Press OK to delete')" href="{{url_for('appointment_bp.delete_appointment', appointment_id=appointment[0])}}">Delete this appointment</a>
                <a href="{{url_for('report_bp.report_page', appointment_id=appointment[0])}}">Update this Report</a>
            </section>
        </section>
    {% endfor %}
</section>
{% endblock info_section %}

project/webAdmin/templates/moreInfo.html
{% extends 'base.html' %}
{% block css %}
<link rel="stylesheet" href="{{url_for('admin.static', filename='css/more-info.css')}}">
<link rel="stylesheet" href="{{url_for('static', filename='css/all-records.css')}}">
{% endblock %}
{% block info_section %}    
    <section class="allRecords">
        <p>Status: {{appointment[1]}}</p>
        <p>Date: {{appointment[3]}}</p>
        <p>Time Slot: {{appointment[4]}}</p>
        <p>venue: {{appointment[5]}}</p>
        <p>Employee: {{appointment[9]}}</p>
        <p>Service: {{service[1]}} - Price: ${{ service[3] }}</p>
        {%for report in report_list%}
            <p>Client report: {{report[3]}}</p>
            <p>Client report: {{report[4]}}</p>
        {%endfor %}
    </section>
{% endblock info_section %}

project/webAdmin/templates/myAppointments.html
{% extends 'base.html' %}
{% block css %}
<link rel="stylesheet" href="{{url_for('static', filename='css/all-records.css')}}">
<link rel="stylesheet" href="{{url_for('admin.static', filename='css/myappointment.css')}}">
<link rel="stylesheet" href="{{url_for('appointment_bp.static', filename='css/appointment.css')}}">
{% endblock %}
{% block info_section %}
    {% if all_appointments_length %}
        {% for appointment in appointments_list %}
        <section class="allRecords">
            <p>Status: {{appointment[1]}}</p>
            <p>Date: {{appointment[3]}}</p>
            <p>Time Slot: {{appointment[4]}}</p>
            <p>venue: {{appointment[5]}}</p>
            {% if current_user.type == "Client" %}
                <p>Employee: {{appointment[9]}}</p>
            {% else %}
                <p>Client: {{appointment[8]}}</p>
            {% endif %}
            <section class="record-buttons">
                <a href="{{url_for('admin.app_info',id=appointment[0])}}">Click for more Info</a>
                <a href="{{url_for('report_bp.report_page', appointment_id=appointment[0])}}">Report</a>
                <a href="{{url_for('appointment_bp.update_appointment', appointment_id=appointment[0])}}">Update</a>
                <a onclick="return confirm('Press OK to delete')" href="{{url_for('appointment_bp.delete_appointment', appointment_id=appointment[0])}}">Delete</a>
            </section>
        </section>
        {% endfor %}
    {% else %}
        <section class="no-appointments">
            <p>You currently have no appointments.</p>
            {% if current_user.type != "Employee" %}
                <a href="{{url_for('appointment_bp.create_appointment')}}">Create an appointment</a>
            {% endif %}
        </section>
    {% endif %}
{% endblock info_section %}

{% block forms_section %}
    {% if all_appointments_length %}
        <form method="POST">
            {{ filter_form.hidden_tag() }}

            <fieldset>
                <legend>Status:</legend>

                {% for subfield in filter_form.filter %}
                    {{ subfield }}
                    {{ subfield.label }}
                {% endfor %}
            </fieldset>
            

            <fieldset>
                <legend>Sort:</legend>

                {% for subfield in filter_form.sort %}
                    {{ subfield }}
                    {{ subfield.label }}
                {% endfor %}
            </fieldset>

            {{ filter_form.submit }}
        </form>
    {% endif %}
{% endblock %}

project/webAdmin/templates/profile.html
{%extends 'base.html'%}
{% block css %}
<link rel="stylesheet" href="{{url_for('admin.static', filename='css/profile.css')}}">
<link rel="stylesheet" href="{{url_for('static', filename='css/all-records.css')}}">
{% endblock %}
{%block nav%}
    <a href="{{url_for('admin.update',user_id=current_user.user_id)}}">Update Profile</a>
    <a onclick="return confirm('Press OK to delete')" href="{{url_for('admin.delete',user_id=current_user.user_id)}}">Delete Profile</a>
{%endblock nav%}
{%block info_section%}
    <section class="allRecords">
        <p>Name: {{current_user['username']}}</p>
        <p>Type: {{current_user['type']}}</p>
        <p>Access Level: {{current_user['access']}}</p>
        <p>Email: {{current_user['email']}}</p>
        <p>Phone Number: {{current_user['phone_number']}}</p>
        <p>Address: {{current_user['address']}}</p>
        <p>Age: {{current_user['age']}}</p>
        {%if current_user['type']=="Employee"%}
            <p>Specialty: {{current_user['specialty']}}</p>
            <p>Pay: {{current_user['pay_rate']}}</p>
        {%endif%}
    </section> 
{%endblock info_section%}

project/webAdmin/templates/update.html
{% extends 'base.html' %}
{% block css %}
<link rel="stylesheet" href="{{url_for('admin.static', filename='css/update-profile.css')}}">
<link rel="stylesheet" href="{{url_for('static', filename='css/all-records.css')}}">
{% endblock %}
{%block js%}
<script src="{{url_for('static',filename='js/formUpdateUser.js')}}"></script>
{%endblock js%}
{% block forms_section %} 
    {%macro render_field (field,plc_holder)%}
        {% if field.errors%}
            {{field(class = 'form-field error-field',placeholder=plc_holder)}}
            <ul>
            {% for error in field.errors%}
                <li>{{error}}</li>
            {%endfor%}
            </ul> 
        {%else%}
            {{field(class = 'form-field success update',placeholder=plc_holder)}}
        {%endif%}
    {%endmacro%} 
    <form action="" method="post" enctype="multipart/form-data" novalidate>
        {{form.hidden_tag()}}
        {{form.type()}}
        {{render_field(form.password,"Enter New Password")}}
        {{render_field(form.email,"Enter New Email")}}
        {{render_field(form.phone_number,"Enter New Phone Number")}}
        {{render_field(form.address,"Enter New Address")}}
        {{render_field(form.age,"Enter New Age")}}
        {{render_field(form.specialty,"Enter New Specialty")}}
        {{render_field(form.pay_rate,"Enter New Pay")}}
        {{render_field(form.user_image,"Enter New Image")}}
        <fieldset id="access_form" class="update">
            {%for subfield in form.access_level%}
                {{subfield.label}}
                {{subfield}}
            {%endfor%}
        </fieldset>
        <fieldset id="active_form" class="update">
            {%for subfield in form.is_active%}
                {{subfield.label}}
                {{subfield}}
            {%endfor%}
        </fieldset>
        
        
        {{form.submit(class='button')}}
    </form>
{% endblock forms_section %}
{%block info_section%}

<section class="allRecords">
    <p>Name: {{user[4]}}</p>
    <p>Type: {{user[2]}}</p>
    <p>Access Level: {{user[3]}}</p>
    <p>Email: {{user[5]}}</p>
    <p>Phone Number: {{user[8]}}</p>
    <p>Address: {{user[9]}}</p>
    <p>Age: {{user[10]}}</p>
    {%if current_user['type']=="Employee"%}
        <p>Specialty: {{user[12]}}</p>
        <p>Pay: {{user[11]}}</p>
    {%endif%}
</section> 

{%endblock info_section%}