project/webAppointment/forms.py
from flask_wtf import FlaskForm
from wtforms import DateField, SelectField, SubmitField, StringField, RadioField
from wtforms.validators import DataRequired
from project.Database.database import db

class CreateAppointment(FlaskForm):
    employee_info = list(map(lambda x: (x[0], f"{x[4]} - Specialty: {x[12]}"), db.get_all_records_cond("salon_user", "user_type = 'Employee'")))
    service_list = list(map(lambda x: (x[0], f"{x[1]} - Price: ${x[3]}"), db.get_all_records("salon_service")))
    
    employee_list = [("", "- Choose the employee -")]
    employee_list.extend(employee_info)

    employee = SelectField("employee", choices=employee_list)
    date = DateField("date")
    time_slot = SelectField("time_slot", choices=[("", "- Choose the time slot -"), ("10:00 AM - 11:00 AM", "10:00 AM - 11:00 AM"), ("2:00 PM - 3:00 PM", "2:00 PM - 3:00 PM"), ("6:00 PM - 7:00 PM", "6:00 PM - 7:00 PM")])
    room = SelectField("room", choices=[("", "- Choose the room -"), (101, "Room 101"), (201, "Room 201"), (301, "Room 301")])
    service = SelectField("service", choices=service_list)

    submit = SubmitField("Create appointment")
    
class UpdateAppointment(CreateAppointment):
    status = SelectField("status", choices=[("open", "Open"), ("closed", "Closed"), ("cancelled", "Cancelled")])
    
    submit = SubmitField("Update appointment")
    
class FilterAppointment(FlaskForm):
    filter = RadioField("filters", choices=[("all", "All"), ("open", "Open"), ("closed", "Closed"), ("cancelled", "Cancelled")], default="all")
    sort = RadioField("filters", choices=[("date", "Date"), ("slot", "Slot"), ("room", "Room"), ("user", "User")], default="date")
    
    submit = SubmitField("Search")

project/webAppointment/routes.py
from flask import Blueprint, flash, redirect,render_template, request, url_for
from flask_login import current_user, login_required
from project.Database.database import db
from project.webAppointment.forms import CreateAppointment, UpdateAppointment, FilterAppointment
import pdb

appointment_bp = Blueprint('appointment_bp',__name__,template_folder='templates',static_folder='static', static_url_path='/appointment_bp/static')

@appointment_bp.route("/appointments", methods=["GET", "POST"])
def list_appointments():
    '''list all appointments'''
    context = {
        "page_title": "Appointments", 
        "main_head": "All Appointments",
        'reports': db.get_all_records('salon_report')}
    appointments = db.get_all_records("salon_appointment")
    appointments_length = len(appointments)
    filter_form = FilterAppointment()
    
    if filter_form.validate_on_submit():   
        if filter_form.filter.data != "all":
            appointments = db.get_all_records_cond("salon_appointment", f"status = '{filter_form.filter.data}'")
            
        if filter_form.sort.data == "date":
            appointments.sort(key=lambda appointment: appointment[3])
        
        if filter_form.sort.data == "slot":
            appointments.sort(key=lambda appointment: appointment[4])
        
        if filter_form.sort.data == "room":
            appointments.sort(key=lambda appointment: appointment[5])
        
        if filter_form.sort.data == "user":
            appointments.sort(key=lambda appointment: appointment[8])
        
    return render_template("appointments.html", context=context, appointments=appointments, filter_form=filter_form, appointments_length=appointments_length, current_user=current_user)

@appointment_bp.route("/create-appointment", methods=["POST", "GET"])
@login_required
def create_appointment():
    '''create new appointment'''
    context = {"page_title": "Create appointment", "main_head": "Creating an appointment"}
    form = CreateAppointment()

    if form.validate_on_submit():
        employee = db.get_one_person(f"user_id = {int(form.employee.data)}")

        db.add_new_appointment(form.date.data, form.time_slot.data, form.room.data, current_user.user_id, employee[0], current_user.username, employee[4], form.service.data)
        
        db.add_new_log(current_user.username, f"Created new appointment on {form.date.data} with {employee[4]}.")
        
        flash("Appointment created successfully!")
        return redirect(url_for("admin.my_appointments"))

    return render_template("create_appointment.html", context=context, form=form)

@appointment_bp.route("/updateappointment/<appointment_id>", methods=["GET", "POST"])
@login_required
def update_appointment(appointment_id):
    '''update appointment'''
    context = {"page_title": "Update appointment", "main_head": "Updating an appointment"}
    appointment = db.get_one_record("salon_appointment", f"appointment_id = {appointment_id}")

    if current_user.access!=4 and current_user.user_id!=appointment[6] and current_user.user_id!=appointment[7]:
        flash("You do NOT have access to this page.","error")
        db.edit_record("is_active=2",f"where user_id={current_user.user_id}","salon_user")
        return redirect(url_for("main_bp.home"))

    form = UpdateAppointment(employee=appointment[7], date=appointment[3], time_slot=appointment[4], room=appointment[5], service=appointment[10], status=appointment[1])
    
    if form.validate_on_submit():
        new_employee = db.get_one_person(f"user_id = {int(form.employee.data)}")
    
        db.edit_record(f"status = '{form.status.data}', date_appointment = TO_DATE('{form.date.data}', 'YYYY-MM-DD'), slot = '{form.time_slot.data}', venue = '{form.room.data}', employee_id = {new_employee[0]}, employee_name = '{new_employee[4]}', service_id = {form.service.data}",
                    f"where appointment_id = {appointment_id}", "salon_appointment")
        db.edit_record(f"status = '{form.status.data}'", f"where appointment_id = {appointment_id}", "salon_report")
        
        db.add_new_log(current_user.username, f"Edited user {appointment[8]}'s appointment. #{appointment[0]}")
            
        flash("Appointment updated successfully.", "success")
        return redirect(url_for("admin.my_appointments"))
    
    return render_template("update_appointment.html", context=context, form=form, appointment=appointment)

@appointment_bp.route("/deleteappointment/<appointment_id>", methods=["GET", "POST"])
@login_required
def delete_appointment(appointment_id):
    '''delete appointment'''
    record_to_delete=db.get_one_record("salon_appointment",f"appointment_id={appointment_id}")
        
    if current_user.access!=4 and current_user.user_id!=record_to_delete[6] and current_user.user_id!=record_to_delete[7]:
        flash("You do NOT have access to this page.","error")
        db.edit_record("is_active=2",f"where user_id={current_user.user_id}","salon_user")
        return redirect(url_for("main_bp.home"))
    
    db.delete_record(f"salon_appointment where appointment_id = {appointment_id}")
    
    db.add_new_log(current_user.username, f"Deleted user {record_to_delete[8]}'s appointment. #{record_to_delete[0]}")
    
    flash("Appointment successfully deleted.", "success")
    return redirect(url_for("admin.my_appointments"))
    

project/webAppointment/templates/appointments.html
{% extends "base.html" %}
{% block css %}
<link rel="stylesheet" href="{{url_for('static', filename='css/all-records.css')}}">
<link rel="stylesheet" href="{{url_for('appointment_bp.static', filename='css/appointment.css')}}">
{% endblock %}
{% block info_section %}
    {% if appointments_length %}
        {% for appointment in appointments %}
            <section class="allRecords">
                <p>Status: {{appointment[1]}}</p>
                <p>Date: {{appointment[3]}}</p>
                <p>Time Slot: {{appointment[4]}}</p>
                <p>Room: {{appointment[5]}}</p>
                <p>Client: {{appointment[8]}}</p>
                <p>Employee: {{appointment[9]}}</p>
                {%if current_user.access==3 or current_user.access==4%}
                    <section class="record-buttons">
                        <a href="{{url_for('appointment_bp.update_appointment', appointment_id=appointment[0])}}">Update this appointment</a>
                        <a onclick="return confirm('Press OK to delete')" href="{{url_for('appointment_bp.delete_appointment', appointment_id=appointment[0])}}">Delete this appointment</a>
                        <a href="{{url_for('report_bp.report_page', appointment_id=appointment[0])}}">Update this Report</a>
                    </section>
                {%endif%}
            </section>
        {% endfor %}
    {% else %}
        <section class="no-appointments">
            <p>There are currently no appointments.</p>
            {% if current_user.is_authenticated and current_user.type != "Employee" %}
                <a href="{{url_for('appointment_bp.create_appointment')}}">Create an appointment</a>
            {% endif %}
        </section>
    {% endif %}
{% endblock %}

{% block forms_section %}
    {% if appointments_length %}
        <form method="POST">
            {{ filter_form.hidden_tag() }}

            <fieldset>
                <legend>Status:</legend>

                {% for subfield in filter_form.filter %}
                    {{ subfield }}
                    {{ subfield.label }}
                {% endfor %}
            </fieldset>
            

            <fieldset>
                <legend>Sort:</legend>

                {% for subfield in filter_form.sort %}
                    {{ subfield }}
                    {{ subfield.label }}
                {% endfor %}
            </fieldset>

            {{ filter_form.submit }}
        </form>
    {% endif %}
{% endblock %}

project/webAppointment/templates/create_appointment.html
{% extends "base.html" %}

{% block css %}
    <link rel="stylesheet" href="{{url_for('appointment_bp.static', filename='css/create-appointment.css')}}">
{% endblock %}

{% block js %}
    <script src="{{ url_for('static', filename='js/formDate.js') }}"></script>
{% endblock %}

{% block forms_section %}
    <form method="POST">
        {{ form.hidden_tag() }}

        {{ form.employee() }}
        {{ form.date() }}
        {{ form.time_slot() }}
        {{ form.room() }}
        {{ form.service() }}

        {{ form.submit() }}
    </form>
{% endblock %}

project/webAppointment/templates/update_appointment.html
{% extends "base.html" %}
{% block css %}
<link rel="stylesheet" href="{{url_for('static', filename='css/all-records.css')}}">
<link rel="stylesheet" href="{{url_for('appointment_bp.static', filename='css/update-appointment.css')}}">
{% endblock %}

{% block js %}
    <script src="{{ url_for('static', filename='js/formDate.js') }}"></script>
{% endblock %}

{% block forms_section %}
    <form method="POST">
        {{ form.hidden_tag() }}

        {{ form.employee() }}
        {{ form.date() }}
        {{ form.time_slot() }}
        {{ form.room() }}
        {{ form.service() }}
        {{ form.status() }}

        {{ form.submit() }}
    </form>
{% endblock %}

{% block info_section %}    
    <section class="allRecords">
        <p>Date: {{appointment[3]}}</p>
        <p>Time Slot: {{appointment[4]}}</p>
        <p>venue: {{appointment[5]}}</p>
        <p>Employee: {{appointment[9]}}</p>
        <p>Service: </p>
    </section>
{% endblock info_section %}